### ISSUE TITLE
Does this require another library for proxy use?

### ISSUE THREAD

**Issue by EM5813** [Nv7-GitHub/googlesearch#29]
I'm getting error 

For a simple example search with proxy 

`search("example search", proxy="http://191.243.218.249:53281")`

I get the error:  

 Max retries exceeded with url: /search?q=something&num=12&hl=en&start=0 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1108)')))

**Any suggestions to fix?**

I've tried to solve with https://stackoverflow.com/questions/33410577/python-requests-exceptions-sslerror-eof-occurred-in-violation-of-protocol

**Comment by Themis3000** [comment]
This library does not require another library for proxy use, that functionality is built into the requests library this depends on.

Does this only occur when using a proxy or does the same thing still happen even when not using a proxy?

**Comment by EM5813** [comment]
Ok working now no problem. Just trying to solve the 429 issue.  Read through this https://github.com/Nv7-GitHub/googlesearch/issues/18

There's got to be a way. I've tried delaying each batch of requests by a few seconds with no luck.

**Comment by Themis3000** [comment]
Since it's google's servers rejecting the request and sending a 429 response code, it's kinda out of our hands. If they just blocked your ip address, there's no bypassing it unless you use a proxy to make requests from another ip that isn't blocked.

My best suggestion would be to try hosting it elsewhere or use some sort of other method to request from a different ip address because if there's an ip block the only way of getting around it is using a different ip address.

**Comment by EM5813** [comment]
Thanks so much
