### ISSUE TITLE
Google cloud plateform error 429

### ISSUE THREAD

**Issue by denistunis13** [Nv7-GitHub/googlesearch#30]
Good Morning,

I have a 429 error when I use Google search on Google cloud plateform ( Google functions) but I don't have errors when I use it directly on my workstation. Have you got an Idea ?

**Comment by Themis3000** [comment]
Google is very strict about blocking automated requests, so google is probably recognizing that you are using a non-residential ip address when your code is deployed on google cloud platform and that's why the requests are being blocked.

There is not really a way around this besides paying google for using their official api unfortunately. This package is great and very well-suited for personal automation and fun projects, but not so suited for deploying at scale or anything critical you rely on because google is so strict about automated requests.

**Comment by Nv7-GitHub** [comment]
This has been resolved, so I'm going to close this
